name: gifterest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.9.0 <3.0.0"

dependency_overrides:
  firebase_auth_platform_interface: 6.1.11
  cloud_firestore_platform_interface: 5.4.13
  flutter_local_notifications_platform_interface: 5.0.0

dependencies:
  firebase_core: ^1.5.0
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  firebase_messaging: ^10.0.5
  google_sign_in: ^5.0.7
  the_apple_sign_in: ^1.1.1
  provider: ^6.0.0
  flutter_slidable: ^0.6.0
  intl: ^0.17.0
  uuid: ^3.0.4
  google_fonts: ^2.1.0
  flutter_markdown: ^0.6.8

  test: ^1.16.0
  email_validator: ^2.0.1
  flutter_material_pickers: ^3.1.0
  url_launcher: ^6.0.9
  tab_indicator_styler: ^2.0.0
  get_it: ^7.2.0
  page_transition: ^2.0.2
  font_awesome_flutter: ^9.1.0
  auto_size_text: 3.0.0-nullsafety.0

  after_layout: ^1.1.0
  loading_animations: ^2.2.0
  top_snackbar_flutter: ^1.0.0
  line_icons: ^2.0.1
  flutter_local_notifications: ^4.0.1

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  mockito: ^5.0.15
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  background_image: assets/splash_screen_background.png
  image: assets/splash_screen_logo.png
  android: true
  ios: true
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/bonobo_icon_ios.png"
  # android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/bonobo_logo.png
    - assets/carita.png
    - assets/logo_circle.png
    - assets/placeholder.jpg
    - assets/google_logo.jpg
    - assets/apple_logo.jpg
    - assets/logo_transpa.png
    - assets/monkey.png
    - assets/broken_heart.png
    - assets/congrats.png
    - assets/fantasmita.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Black.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins/Poppins-Light.ttf
        - asset: fonts/Poppins/Poppins-Medium.ttf
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
        - asset: fonts/Poppins/Poppins-Thin.ttf
    - family: Nunito-Sans
      fonts:
        - asset: fonts/Nunito_Sans/NunitoSans-Black.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-Bold.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-ExtraBold.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-ExtraLight.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-Light.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-Regular.ttf
        - asset: fonts/Nunito_Sans/NunitoSans-SemiBold.ttf
    - family: Mulish
      fonts:
        - asset: fonts/Mulish/Mulish-VariableFont_wght.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
